### ISSUE TITLE
Geonames ontology URI

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/geonames-harvest#1]
The current mapping uses an http**s** URI for the Geonames ontology.

https://github.com/netwerk-digitaal-erfgoed/geonames-harvest/blob/48fc4a1541fcadc7ec99cfdad1eaac7f6cc45f81/geonames.rml#L8

The URI Geonames itself references for its ontology is http://www.geonames.org/ontology#  (so without the **s**) as does prefix.cc.

PS. the Geonames URIs for resources are (correctly) using http**s**

**Comment by EnnoMeijers** [comment]
I guess Geonames itself is being sloppy here. I used the formal ontology definition as starting point: https://www.geonames.org/ontology/ontology_v3.2.rdf. This defines the base prefix as http**s**. Do we run into problems using somewhere using http**s**?

**Comment by coret** [comment]
Oh my, sloppy indeed.
We won't run into problems because it's an "isolated" dataset and ontology. If people started adding RDF from Geonames directly (very unlikely because very rate-limited), than you would have both http/https and queries then also have to be "doubled" or miss out on triples...

Another example for https://github.com/w3c/sparql-12/issues/156

**Comment by ivozandhuis** [comment]
There is not only a difference in httpS or not but in subdomain "www." or "sws." as well!

**Comment by EnnoMeijers** [comment]
Based on the [Geonames documentation](http://www.geonames.org/ontology/documentation.html) I have used 'www' for the ontology and 'sws' for the entities.

**Comment by ivozandhuis** [comment]
Yes, but your prefix on line 8 has "sws."?

**Comment by EnnoMeijers** [comment]
Check, that's an error!

**Comment by ivozandhuis** [comment]
Change in line 8 of rml-file:
`@prefix gn: <https://sws.geonames.org/ontology#>.` 
into 
`@prefix gn: <https://www.geonames.org/ontology#>.`

**Comment by EnnoMeijers** [comment]
Fixed in https://github.com/netwerk-digitaal-erfgoed/geonames-harvest/commit/c805769ae622e6802ca6746e39bbd00860093dd5
