### ISSUE TITLE
Current config needs manual rework

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/geonames-harvest#10]
In the current config map.sh writes the result RDF set back to the $DATADIR. This needs to be the 'fuseki/databases' dir in order to make it available through Fuseki.

**Comment by ddeboer** [comment]
The import script (`map.sh`) should not depend on the SPARQL server used for publication (Fuseki). Have a look at [our infrastructure config](https://github.com/netwerk-digitaal-erfgoed/infrastructure/blob/master/k8s/geonames-sparql/geonames-sparql-stateful-set.yml#L26-L31) to find out how you can parameterise Fuseki to look at the data in a custom place:

          args: ["--file=/data/geonames.nt", "/geonames"]
          ports:
            - containerPort: 3030
          volumeMounts:
            - name: data
              mountPath: /data

You should be able to change this in `server.sh`.

**Comment by EnnoMeijers** [comment]
Ok clear! But this doesn't work for local deployment because the output file can not be reached by the container unless it is on the available on the mounted volume. Let discuss this offline sometime.
