### ISSUE TITLE
Change to the harvester is not propageted

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/geonames-harvest#16]
The recent change to revert the download of the DE places is not being propagated to the server, the German places are still in the results.

**Comment by ddeboer** [comment]
The change has been applied now. Kubernetes preferring stateless apps, we’re having some problems with sharing our state in a persistent volume between multiple containers (harvester and SPARQL server): https://github.com/netwerk-digitaal-erfgoed/infrastructure/issues/40.
