### ISSUE TITLE
Close geonames-URI with "/"

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/geonames-harvest#3]
https://github.com/netwerk-digitaal-erfgoed/geonames-harvest/blob/48fc4a1541fcadc7ec99cfdad1eaac7f6cc45f81/geonames.rml#L32

I'm not sure (reading my first RML :-), but I think the geonames URI should end with a "/". (If you open an rdf-representation of a resource you can see this in the rdf:about attribute of the RDF/XML eg. https://sws.geonames.org/2750821/about.rdf)

**Comment by EnnoMeijers** [comment]
Fixed in https://github.com/netwerk-digitaal-erfgoed/geonames-harvest/commit/c805769ae622e6802ca6746e39bbd00860093dd5
