### ISSUE TITLE
Automate harvest and publication

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/geonames-harvest#4]
Refactor the scripts so the harvest and publication is fully automated and Docker based.

**Comment by EnnoMeijers** [comment]
@ddeboer could you have a look at the new setup with the Fuseki Docker and suggest next steps for deploying this in the NDE infra?

**Comment by ddeboer** [comment]
To do:

- [x] Run harvest in container.
- [x] Run that container as a K8s init container.
- [x] Schedule the init container with a K8s CronJob.

**Comment by ddeboer** [comment]
GeoNames is now available at https://demo.netwerkdigitaalerfgoed.nl/geonames/sparql.
