### ISSUE TITLE
Map parentCountry

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/geonames-harvest#7]
Can we map parentCountry in the RDF at https://sws.geonames.org/2752375/about.rdf? It would be great to add that to skos:broader, so users can differentiate better between the same place names in different countries.

**Comment by EnnoMeijers** [comment]
A simple solution without touching the data is to add the countryCode to prefLabel in the query. The countryCode is always available in the data. This way Middelburg becomes either Middelburg (NL) or Middelburg (BE). This change is proposed in https://github.com/netwerk-digitaal-erfgoed/network-of-terms/compare/master...feat-geo
